version: 0.0.{build}
image: Visual Studio 2017 Preview
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - nuget restore
build:
  publish_wap: true
  verbosity: minimal
deploy:
- provider: WebDeploy
  server: 
    secure: PIlYeDqNoP4Bh5C6FO5/kyXE3KFX0q6aEeMaFjteDfzkM6nMvoqA5GPZqPaWPXfNaqvpZvxyIKokIeqct+KenXhzcp3y/f8e05o3YIncVYg=
  website: GoedeDoelenHelpen
  username: $GoedeDoelenHelpen
  password:
    secure: Gta6kVSNFhlosj6KZ8eDPs//BQtatFuLyG2dkkEqd8PHS88J1Q8iFCA+dPmQWI9e0R3Wcn8dfeSEwCjXJAeH3A==
  aspnet_core: true
  aspnet_core_force_restart: true
  on:
    branch: develop
notifications:
- provider: Slack
  incoming_webhook: 
    secure: r9WG7/hHyN6WxlOGaEShrXvmIcbhHogbqaXFIrIyAEgfuxmUwvCG9QX/rHfSXBsYrT4IfMd5qrTs2MCk0+As4c4GhUUHi+r/57tmQmafi7M=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
