version: 0.2.{build}
image: Visual Studio 2017 Preview
platform: x86
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - ps: Install-Product node 10
before_build:
  - nuget restore
build:
  publish_wap_xcopy: true
  verbosity: normal
build_script:
  # output will be in ./GoedeDoelenHelpen/bin/x86/Debug/netcoreapp2.1/publish
  - cmd: dotnet publish ./GoedeDoelenHelpen/GoedeDoelenHelpen.csproj
after_build:
  - ps: cd ./GoedeDoelenHelpen/ClientApp
  - ps: npm run build-ci
artifacts:
- path: ./GoedeDoelenHelpen/bin/x86/Debug/netcoreapp2.1/publish/
  name: GoedeDoelenHelpen
  type: Zip
deploy:
- provider: AzureAppServiceZipDeploy
  aspnet_core_force_restart: true
  appservice_environment: true
  website: goededoelenhelpen
  username: $GoedeDoelenHelpen
  password:
    secure: Gta6kVSNFhlosj6KZ8eDPs//BQtatFuLyG2dkkEqd8PHS88J1Q8iFCA+dPmQWI9e0R3Wcn8dfeSEwCjXJAeH3A==
  appservice_environment_name: GoedeDoelenHelpen
  on:
    branch: develop
notifications:
- provider: Slack
  incoming_webhook: 
    secure: r9WG7/hHyN6WxlOGaEShrXvmIcbhHogbqaXFIrIyAEgfuxmUwvCG9QX/rHfSXBsYrT4IfMd5qrTs2MCk0+As4c4GhUUHi+r/57tmQmafi7M=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
